### ISSUE TITLE
0.5.0 Tracking Issue

### ISSUE THREAD

**Issue by JonahPlusPlus** [JonahPlusPlus/bevy_atmosphere#30]
Things to do when Bevy 0.9 is released.

- [x] Update to be 0.9 compliant

QOL changes:
- ~~Remove `AtmosphereSkyBoxMaterial` (unnecessary newtype) or make it an alias~~ (Bevy 0.9 now requires `impl Resource`, so the `Handle` can't be used directly)
- [x] Add default `procedural` feature (controls whether the `AtmospherePlugin` adds the `AtmospherePipelinePlugin`) (Fixes #29)
- [x] Add removal detection to `detection` feature
- ~~Remove dithering (Bevy 0.9 now adds dithering by default)~~ (dithering is still necessary, it seems banding still occurs)
- [x] Explore compile time vs run time discrepancy (see more below)
- [x] Rename compute shader "time" variables to "depth" (to make it more accurate to the source literature)
- [x] Add more images to README

Potential Features:
- [x] Alternative sky models (Added `Gradient` model)
- ~~Night sky model (Fixes #27)~~

### Compile time vs run time discrepancy 
As more features get added in, I should put more consideration into how things are organized. Sky models, for instance, can be organized into an enum and the variants can be feature-gated. In that case, the enum should be marked non-exhaustive, so changing the variant features won't cause a compile error. Besides that, it allows for adding new sky models in the future.

On that note, I should probably see if current features can receive the same treatment (allow for changing behavior at compile time and run time) to make them more flexible.
