### ISSUE TITLE
0.6.0 Tracking Issue

### ISSUE THREAD

**Issue by JonahPlusPlus** [JonahPlusPlus/bevy_atmosphere#42]
A tracking issue for things to do for the Bevy 0.10 release.

## Bevy groundwork
Some of the changes I want require Bevy support.
- [ ] Optional/Resultful System Params (to support `Option<Atmosphere>`) (in progress)
- [ ] Custom Asset Loading (to support loading cube textures)
- [x] Unsized `AsBindGroup` (to clean up `Atmospheric` trait) ([merged](https://github.com/bevyengine/bevy/pull/6937))

## QOL Changes
- [ ] Create way to disable auto-rotation (#39)
- [ ] Remove mesh bloat by instancing a single skybox mesh and scale it to fit the camera far plane? (Add a new system for auto-scaling the cube to respond to changes with the camera far plane?)
- [ ] Add an FAQ for common problems (notably #40)
- [ ] Rename models to have a -`Model` suffix (See `ImageModel` below, `Image` is already a Bevy type) for consistency

## Features
- [ ] Layer System (#41)
- [ ] Add `ImageModel`
- [ ] Add PBL support ([open](https://github.com/bevyengine/bevy/pull/7051))
- [ ] Add more accurate sky model for PBL?
